name: Fix svg fill

on:
  push:
    branches-ignore:
      - main
    paths:
      - packages/icons/**

jobs:
  fixFill:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Fix fill
        run: cd packages/icons && yarn fix-fill

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Fix svg fill'
          add: 'packages/icons/src/*.svg'
